name: prueba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.0.15 
  path_provider: ^2.0.11


  
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/restaurant_icon.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/